@echo off
chcp 65001 >nul
setlocal EnableDelayedExpansion

title Q-Mol v2.0.0 — Local Development Server
cls

echo  ╔══════════════════════════════════════════════════════════════════╗
echo  ║                    Q-Mol v2.0.0 Development                      ║
echo  ║         Molecular Informatics Platform — Local Start               ║
echo  ╚══════════════════════════════════════════════════════════════════╝
echo.

set "PROJECT_DIR=D:\Qmol-3"
set "PYTHON=%PROJECT_DIR%\.venv\Scripts\python.exe"
set "PIP=%PROJECT_DIR%\.venv\Scripts\pip.exe"
set "VENV_DIR=%PROJECT_DIR%\.venv"
set "ENV_FILE=%PROJECT_DIR%\.env"
set "DATA_DIR=%PROJECT_DIR%\data"
set "LOGS_DIR=%PROJECT_DIR%\logs"
set "JOBS_DIR=%PROJECT_DIR%\jobs"
set "PORT=8000"
set "API_URL=http://localhost:%PORT%"

cd /d "%PROJECT_DIR%"

:: =============================================
:: 1. CHECK PYTHON VENV
:: =============================================
echo [1/8] Checking Python environment...
if exist "%PYTHON%" (
    echo     ✓ Python found: %PYTHON%
    "%PYTHON%" -c "import sys; print('     Python version:', sys.version.split()[0])" 2>nul
) else (
    echo     ✗ Python not found at %PYTHON%
    echo     Trying system Python...
    where python >nul 2>&1
    if errorlevel 1 (
        echo     ✗ Python not found on system.
        echo.
        echo     Please install Python 3.10+ and create a venv:
        echo       python -m venv .venv
        echo       .venv\Scripts\activate
        echo       pip install -r requirements.txt
        echo.
        pause
        exit /b 1
    ) else (
        set "PYTHON=python"
        set "PIP=pip"
        echo     ✓ Using system Python
    )
)

:: =============================================
:: 2. CHECK .env FILE
:: =============================================
echo [2/8] Checking environment configuration...
if not exist "%ENV_FILE%" (
    echo     ! .env file not found — creating from template...
    (
        echo # Q-Mol Local Development Environment
        echo # Auto-generated by start.bat on %DATE%
        echo.
        echo # Database
        echo USE_POSTGRES=false
        echo DATABASE_URL=postgresql+asyncpg://qmol:qmol@localhost:5432/qmol
        echo REDIS_URL=redis://localhost:6379/0
        echo.
        echo # Security
        echo QMOL_ADMIN_TOKEN=dev_admin_token_change_in_production
        echo API_KEY_PEPPER=local_dev_pepper_change_me
        echo.
        echo # Billing (optional — disable for local dev)
        echo STRIPE_SECRET_KEY=
        echo STRIPE_WEBHOOK_SECRET=
        echo STRIPE_PUBLISHABLE_KEY=
        echo.
        echo # App
        echo QMOL_PUBLIC_URL=http://localhost:8000
        echo ALLOWED_ORIGINS=http://localhost:8000,http://localhost:5173
        echo ALLOWED_HOSTS=localhost
        echo TRUSTED_PROXIES=
        echo HTTPS_ONLY=false
        echo.
        echo # Celery
        echo CELERY_BROKER_URL=redis://localhost:6379/0
        echo CELERY_RESULT_BACKEND=redis://localhost:6379/0
        echo.
        echo # Quantum (optional)
        echo IBM_QUANTUM_TOKEN=
    ) > "%ENV_FILE%"
    echo     ✓ Created .env file (edit it for production settings)
) else (
    echo     ✓ .env file exists
)

:: =============================================
:: 3. CREATE DIRECTORIES
:: =============================================
echo [3/8] Creating data directories...
if not exist "%DATA_DIR%" mkdir "%DATA_DIR%"
if not exist "%LOGS_DIR%" mkdir "%LOGS_DIR%"
if not exist "%JOBS_DIR%" mkdir "%JOBS_DIR%"
echo     ✓ data/ logs/ jobs/ directories ready

:: =============================================
:: 4. INSTALL DEPENDENCIES
:: =============================================
echo [4/8] Checking Python dependencies...
"%PYTHON%" -c "import fastapi" 2>nul
if errorlevel 1 (
    echo     ! Dependencies not installed — installing...
    if exist "%PIP%" (
        "%PIP%" install -r requirements.txt 2>&1 | findstr /i "Successfully installed\|error\|ERROR"
    ) else (
        "%PYTHON%" -m pip install -r requirements.txt 2>&1 | findstr /i "Successfully installed\|error\|ERROR"
    )
    if errorlevel 1 (
        echo     ✗ Failed to install dependencies
        pause
        exit /b 1
    )
    echo     ✓ Dependencies installed
) else (
    echo     ✓ Dependencies already installed
)

:: =============================================
:: 5. SYNTAX CHECK ALL PYTHON FILES
:: =============================================
echo [5/8] Running syntax check on all Python files...
"%PYTHON%" -c "
import py_compile, os, sys
errors = []
checked = 0
for root, dirs, files in os.walk('src'):
    for f in files:
        if f.endswith('.py'):
            path = os.path.join(root, f)
            try:
                py_compile.compile(path, doraise=True)
                checked += 1
            except Exception as e:
                errors.append((path, e))

# Also check root files
for f in ['api.py', 'config.py', 'cli.py', 'worker.py', 'stripe_checkout.py', 'stripe_webhook.py']:
    if os.path.exists(f):
        try:
            py_compile.compile(f, doraise=True)
            checked += 1
        except Exception as e:
            errors.append((f, e))

print(f'     Checked {checked} files — {len(errors)} errors')
for p, e in errors[:5]:
    print(f'     ✗ {p}: {e}')
if len(errors) > 5:
    print(f'     ... and {len(errors)-5} more')
if errors:
    sys.exit(1)
" 2>&1

if errorlevel 1 (
    echo     ✗ Syntax errors found — fix them before starting
    pause
    exit /b 1
)
echo     ✓ All Python files compile cleanly

:: =============================================
:: 6. RUN INTEGRATION TESTS
:: =============================================
echo [6/8] Running integration tests...
"%PYTHON%" -m pytest tests/integration/test_api.py -v --tb=short 2>&1 | findstr /i "passed\|failed\|error\|ERROR\|FAILED"
if errorlevel 1 (
    echo     ! Tests returned errors — continuing anyway (may be SQLite-only tests)
) else (
    echo     ✓ Tests completed
)

:: =============================================
:: 7. START API SERVER
:: =============================================
echo [7/8] Starting Q-Mol API server...
echo.
echo     ═══════════════════════════════════════════════════════
echo     API will be available at: %API_URL%
echo     Health check: %API_URL%/v1/health
echo     API docs:     %API_URL%/v1/docs
echo     ═══════════════════════════════════════════════════════
echo.
echo     Press Ctrl+C to stop the server
echo.

:: Open browser tabs in background
start "" "%API_URL%/v1/docs"
start "" "%API_URL%/v1/health"

:: Start the server with uvicorn
"%PYTHON%" -m uvicorn api:app --host 0.0.0.0 --port %PORT% --reload --log-level info

:: If uvicorn fails, try with the python module directly
if errorlevel 1 (
    echo.
    echo     ! uvicorn failed — trying direct Python execution...
    "%PYTHON%" -c "import uvicorn; uvicorn.run('api:app', host='0.0.0.0', port=%PORT%, reload=True)" 2>&1
)

:: =============================================
:: 8. CLEANUP / RESTART
:: =============================================
echo.
echo Server stopped.
echo.
set /p RESTART="Restart server? (y/n): "
if /i "%RESTART%"=="y" goto :start

:open_folder
:: Open project folder in Explorer
start "" "explorer.exe" "%PROJECT_DIR%"

echo.
echo Done. Project folder opened.
pause
endlocal
