apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "qmol.fullname" . }}-config
  labels:
    {{- include "qmol.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.env }}
  {{ $key | lower | replace "_" "-" }}: {{ $value | quote }}
  {{- end }}
  database-url: {{ include "qmol.databaseUrl" . | quote }}
  redis-url: {{ include "qmol.redisUrl" . | quote }}
