apiVersion: v1
kind: Service
metadata:
  name: {{ include "qmol.fullname" . }}-flower
  labels:
    {{- include "qmol.labels" . | nindent 4 }}
    app.kubernetes.io/component: flower
spec:
  type: {{ .Values.service.flower.type }}
  ports:
    - port: {{ .Values.service.flower.port }}
      targetPort: {{ .Values.service.flower.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "qmol.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: flower
