#!/usr/bin/env python3
"""Q-Mol One-Click Setup — Plug & Play Configuration.

Run this script to fully configure Q-Mol for production use:
- Sets up .env file with sensible defaults
- Validates the environment
- Runs smoke tests
- Generates a startup report

Usage:
    python scripts/setup_plug_and_play.py
"""
from __future__ import annotations
import os
import secrets
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ENV_FILE = ROOT / ".env"
DATA_DIR = ROOT / "data"

REQUIRED_DIRS = [
    DATA_DIR,
    DATA_DIR / "jobs",
    ROOT / "logs",
]

ENV_TEMPLATE = """# Q-Mol Production Configuration
# Generated by setup_plug_and_play.py

# Database (SQLite default — no PostgreSQL needed for free tier)
USE_POSTGRES=false
DATABASE_URL=sqlite+aiosqlite:///data/qmol.sqlite

# Redis (optional — for Celery jobs and caching)
# If not running Redis, the app gracefully degrades to in-memory
REDIS_URL=redis://localhost:6379/0

# Security — CHANGE THESE!
API_KEY_PEPPER={pepper}
QMOL_ADMIN_TOKEN={admin_token}

# CORS — update with your domain
ALLOWED_ORIGINS=https://photon-bounce.com,https://api.photon-bounce.com,http://localhost:3000

# Trusted proxies (for X-Forwarded-For in production)
TRUSTED_PROXIES=10.0.0.0/8,172.16.0.0/12,192.168.0.0/16

# Harvesting (data collection for monetization)
ENABLE_HARVEST=true

# Rate limiting (requests per minute per IP)
FREE_RATE_LIMIT=60
PAID_RATE_LIMIT=600

# Email (optional — for magic links and notifications)
# MAILGUN_API_KEY=your-mailgun-key
# MAILGUN_DOMAIN=mg.photon-bounce.com

# Public URL (for magic links and webhooks)
QMOL_PUBLIC_URL=https://api.photon-bounce.com

# Stripe (optional — for credit card payments)
# STRIPE_SECRET_KEY=sk_test_...
# STRIPE_WEBHOOK_SECRET=whsec_...
# STRIPE_PRICE_RESEARCH=price_...
# STRIPE_PRICE_COMMERCIAL=price_...

# Google Play (optional — for Android subscriptions)
# ANDROID_PACKAGE_NAME=com.qmol.app
# GOOGLE_PLAY_SERVICE_ACCOUNT_JSON={...}

# PubChem (optional — for molecule enrichment)
PUBCHEM_START_CID=1
PUBCHEM_BATCH_SIZE=50

# Celery (optional — for async job processing)
CELERY_TASK_TIME_LIMIT=3600
CELERY_TASK_SOFT_TIME_LIMIT=3300
"""


def generate_secrets() -> tuple[str, str]:
    """Generate secure random secrets."""
    pepper = secrets.token_hex(32)
    admin_token = secrets.token_hex(32)
    return pepper, admin_token


def check_environment() -> list[str]:
    """Check that the environment is ready."""
    issues = []
    
    # Check Python version
    if sys.version_info < (3, 11):
        issues.append(f"Python {sys.version_info.major}.{sys.version_info.minor} is too old. Need 3.11+")
    
    # Check virtual environment (search common locations)
    venv_locations = [
        ROOT / ".venv" / "Scripts" / "python.exe",
        Path("D:\\qmol\\.venv") / "Scripts" / "python.exe",
        Path("D:\\Qmol-3\\.venv") / "Scripts" / "python.exe",
    ]
    venv_found = any(p.exists() for p in venv_locations)
    if not venv_found:
        issues.append("Virtual environment not found at .venv/")
    
    # Check RDKit
    try:
        from rdkit import Chem
        _ = Chem.MolFromSmiles("CCO")
    except Exception as e:
        issues.append(f"RDKit not working: {e}")
    
    # Check FastAPI
    try:
        import fastapi
    except ImportError:
        issues.append("FastAPI not installed")
    
    # Check critical files exist
    critical_files = [
        ROOT / "api.py",
        ROOT / "config.py",
        ROOT / "requirements.txt",
    ]
    for f in critical_files:
        if not f.exists():
            issues.append(f"Missing critical file: {f}")
    
    return issues


def setup_directories() -> None:
    """Create required data directories."""
    for d in REQUIRED_DIRS:
        d.mkdir(parents=True, exist_ok=True)
        print(f"  Created: {d}")


def setup_env_file() -> None:
    """Create or update .env file with production settings."""
    if ENV_FILE.exists():
        print(f"  .env already exists at {ENV_FILE}")
        print(f"  To regenerate, delete it and run this script again.")
        return
    
    pepper, admin_token = generate_secrets()
    env_content = ENV_TEMPLATE.replace("{pepper}", pepper).replace("{admin_token}", admin_token)
    ENV_FILE.write_text(env_content, encoding="utf-8")
    
    print(f"  Created: {ENV_FILE}")
    print(f"  IMPORTANT: Save these secrets:")
    print(f"    API_KEY_PEPPER: {pepper[:16]}...")
    print(f"    ADMIN_TOKEN: {admin_token[:16]}...")
    print(f"  Keep them safe — they are not stored elsewhere!")


def smoke_test() -> list[str]:
    """Quick smoke test — import the app and check health."""
    issues = []
    
    try:
        sys.path.insert(0, str(ROOT))
        import api
        
        # Check that the app can be created
        app = api.app
        assert app.title == "Q-Mol API"
        assert app.version == "2.0.0"
        
        # Check that all routers are registered
        routes = [r.path for r in app.routes]
        required = ["/v1/health", "/v1/ready", "/v1/compute", "/v1/signup"]
        for r in required:
            if r not in routes:
                issues.append(f"Missing route: {r}")
        
        print(f"  App loads OK — {len(routes)} routes registered")
        
    except Exception as e:
        issues.append(f"App failed to load: {e}")
    
    return issues


def main():
    print("=" * 60)
    print("  Q-Mol Plug & Play Setup")
    print("=" * 60)
    print()
    
    # 1. Check environment
    print("[1/4] Checking environment...")
    env_issues = check_environment()
    if env_issues:
        print(f"  ERROR: {len(env_issues)} issue(s) found:")
        for issue in env_issues:
            print(f"    - {issue}")
        print()
        print("Please fix the issues above and run this script again.")
        sys.exit(1)
    print("  Environment OK")
    
    # 2. Create directories
    print("[2/4] Setting up directories...")
    setup_directories()
    
    # 3. Create .env
    print("[3/4] Creating configuration...")
    setup_env_file()
    
    # 4. Smoke test
    print("[4/4] Running smoke test...")
    smoke_issues = smoke_test()
    if smoke_issues:
        print(f"  WARNING: {len(smoke_issues)} issue(s):")
        for issue in smoke_issues:
            print(f"    - {issue}")
    else:
        print("  Smoke test passed!")
    
    print()
    print("=" * 60)
    print("  Setup Complete!")
    print("=" * 60)
    print()
    print("Next steps:")
    print("  1. Review .env file and customize as needed")
    print("  2. Start the server:")
    print("     .venv\\Scripts\\python -m uvicorn api:app --host 0.0.0.0 --port 8000")
    print("  3. Run QA cycles:")
    print("     scripts\\qa.bat")
    print("  4. Set up Cloudflare Tunnel (see deploy\\CLOUDFLARE_TUNNEL.md)")
    print()
    print("Your admin dashboard:")
    print(f"  http://localhost:8000/v1/admin/cache")
    print(f"  (use x-admin-token from your .env file)")
    print()


if __name__ == "__main__":
    main()
